DROP DATABASE bookworm_db;

CREATE DATABASE IF NOT EXISTS bookworm_db;

USE bookworm_db;



CREATE TABLE IF NOT EXISTS USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(75) NOT NULL,
    LAST_NAME VARCHAR(75) NOT NULL,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    EMAIL VARCHAR(125) NOT NULL UNIQUE,
    PASSWORD VARCHAR(25) NOT NULL,
    BIO VARCHAR(160),
    PROFILE_PICTURE_PATH VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS BOOKSHELF(
    BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISBN LONG NULL,
    BOOK_TITLE VARCHAR(250) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    DATA_PUBLISHED VARCHAR(75) NOT NULL,
    COVER_PAGE VARCHAR(250),
    DESCRIPTION LONGTEXT NOT NULL,
    GENRE VARCHAR(75) NOT NULL,
    PAGE_COUNT INT NOT NULL,
    RATING INT NOT NULL,
    GOOGLE_PLAY VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS USER_REVIEWS(
    REVIEW_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RATING INT NOT NULL,
    TITLE VARCHAR(250) NOT NULL,
    BODY LONGTEXT NOT NULL,
    BOOKSHELF_ID LONG NOT NULL,
    USER_ID LONG NOT NULL
);


-- Creating the GENRE table
CREATE TABLE GENRE (
   GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255)
);

-- Creating the USER_FAVORITE_GENRE table
CREATE TABLE FAVORITE_GENRE (
     USER_FAVORITE_GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     USER_ID BIGINT,
     GENRE_ID BIGINT,
     FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
     FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
);


